appConfig: weaver.toml
image: h21565897/socialnet-serviceweaver:123456
# repo: ybyan0108/socialnet-serviceweaver

listeners:
  - name: apilistener
    public: true

scalingSpec:
  minReplicas: 1
  maxReplicas: 1

groups:
  - name: scalingMachines
    components: 
      - SocialNetwork/server/IStorage
    scalingSpec:
      minReplicas: 1
      maxReplicas: 1